# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
    - main
    - /^feature\/.$/
    - /^release\/.$/
    - /^(.*\/)?ci-.*$/

pool:
    vmImage: 'windows-2022'

variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

steps:
    -   task: NuGetToolInstaller@

    -   task: UseDotNet@2
        inputs:
            packageType: 'sdk'
            version: '7.x'

    -   task: DotNetCoreCLI@2
        inputs:
            command: 'restore'
            projects: '**/*.csproj'
            feedsToUse: 'select'

    -   task: DotNetCoreCLI@2
        inputs:
            command: 'build'
            projects: '**/*.csproj'

