// Copyright (c) 2014-2020 Sarin Na Wangkanai, All Rights Reserved.
// The Apache v2. See License.txt in the project root for license information.

namespace Wangkanai.Detection.Collections
{
    internal static class MobileCollection
    {
        // mobile device keywords
        public static readonly string[] Keywords = 
        {
            "iphone",
            "mobile",
            "blackberry",
            "phone",
            "smartphone",
            "webos",
            "ipod",
            "lge vx",
            "midp",
            "maemo",
            "mmp",
            "netfront",
            "hiptop",
            "nintendo DS",
            "novarra",
            "openweb",
            "opera mobi",
            "opera mini",
            "palm",
            "psp",
            "smartphone",
            "symbian",
            "up.browser",
            "up.link",
            "wap",
            "windows ce",
            "windows phone"
        };

        // reference 4 character from http://www.webcab.de/wapua.htm
        public static readonly string[] Prefixes =
        {
            "w3c ",
            "w3c-",
            "acs-",
            "alav",
            "alca",
            "amoi",
            "audi",
            "avan",
            "benq",
            "bird",
            "blac",
            "blaz",
            "brew",
            "cell",
            "cldc",
            "cmd-",
            "dang",
            "doco",
            "eric",
            "hipt",
            "htc_",
            "inno",
            "ipaq",
            "ipod",
            "jigs",
            "kddi",
            "keji",
            "leno",
            "lg-c",
            "lg-d",
            "lg-g",
            "lge-",
            "lg/u",
            "maui",
            "maxo",
            "midp",
            "mits",
            "mmef",
            "mobi",
            "mot-",
            "moto",
            "mwbp",
            "nec-",
            "newt",
            "noki",
            "palm",
            "pana",
            "pant",
            "phil",
            "play",
            "port",
            "prox",
            "qwap",
            "sage",
            "sams",
            "sany",
            "sch-",
            "sec-",
            "send",
            "seri",
            "sgh-",
            "shar",
            "sie-",
            "siem",
            "smal",
            "smar",
            "sony",
            "sph-",
            "symb",
            "t-mo",
            "teli",
            "tim-",
            "tosh",
            "tsm-",
            "upg1",
            "upsi",
            "vk-v",
            "voda",
            "wap-",
            "wapa",
            "wapi",
            "wapp",
            "wapr",
            "webc",
            "winw",
            "winw",
            "xda ",
            "xda-"
        };
    }
}
