//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wangkanai.Markdown {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Wangkanai.Markdown.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        internal static string PathMustBeRootRelativePath {
            get {
                return ResourceManager.GetString("PathMustBeRootRelativePath", resourceCulture);
            }
        }
        
        internal static string StateShouldBeNullForRouteValueTransformers {
            get {
                return ResourceManager.GetString("StateShouldBeNullForRouteValueTransformers", resourceCulture);
            }
        }
        
        internal static string InvalidActionDescriptorModelType {
            get {
                return ResourceManager.GetString("InvalidActionDescriptorModelType", resourceCulture);
            }
        }
        
        internal static string ViewLocationFormatsIsRequired {
            get {
                return ResourceManager.GetString("ViewLocationFormatsIsRequired", resourceCulture);
            }
        }
        
        internal static string MarkdownProject_PathMustStartWithForwardSlash {
            get {
                return ResourceManager.GetString("MarkdownProject_PathMustStartWithForwardSlash", resourceCulture);
            }
        }
    }
}
